// Build the dashboard's data files from the raw scans.
//   xhs_authors.json  → dashboard/data.js   (creators to follow, with avatars)
//   me.json           → dashboard/me.js     (your notes, categorized + analyzed)
//
// Both outputs load via <script>, so the dashboard works opened straight from
// disk (file:// blocks fetch). Both are gitignored — tooling is public, your
// data is local.
//
// Categorization + analysis live HERE, not in the puller: pure transform, safe
// to re-run and tweak without spending API calls.
//
// Usage: node scripts/build_dashboard.mjs [--lang en|zh]
//   --lang sets the dashboard's default UI language (the UI also has a live toggle).
//   Category LABELS are bilingual; category KEYWORDS stay Chinese (they match Chinese posts).

import fs from 'node:fs';
import path from 'node:path';

const root = path.resolve(import.meta.dirname, '..');
const langArg = (process.argv.find(a => a.startsWith('--lang')) || '').split('=')[1]
  || (process.argv[process.argv.indexOf('--lang') + 1] === 'en' ? 'en' : null);
const LANG = langArg === 'en' ? 'en' : 'zh';
const read = f => JSON.parse(fs.readFileSync(path.join(root, f), 'utf8'));
const write = (f, obj) => {
  fs.mkdirSync(path.join(root, 'dashboard'), { recursive: true });
  fs.writeFileSync(path.join(root, 'dashboard', f),
    `// Generated by scripts/build_dashboard.mjs — do not edit, gitignored.\nwindow.CM_LANG = ${JSON.stringify(LANG)};\nwindow.${f === 'me.js' ? 'ME' : 'SCAN'} = ${JSON.stringify(obj)};\n`);
};

// ── categories ──────────────────────────────────────────────────────────
// Keyword rules over title+desc. First rule with the most hits wins; ties go
// to rule order. Tune the keyword rules to the account's actual corpus.
const CATS = [
  { key: 'healing',      label: '疗愈 / 爱上生活', en: 'Healing', emoji: '🌿',
    kw: ['疗愈','治愈','爱上生活','幸福感','低成本','清单','小确幸','瞬间','充电','能量','恢复','松弛','解压','哄自己','爱自己','幸福','平静','温暖','晚安'] },
  { key: 'emotion',      label: '情绪 / 自我成长', en: 'Emotion / Growth', emoji: '🌱',
    kw: ['情绪','焦虑','内耗','成长','自洽','心态','感受','intj','mbti','人格','内求','课题','钝感','高敏感','自信','勇敢','别怕','别忘了自己','迷茫','孤独'] },
  { key: 'food',         label: '美食 / 吃喝', en: 'Food', emoji: '🍜',
    kw: ['吃','美食','咖啡','冰咖','探店','餐厅','食谱','奶茶','早餐','夜宵','好吃','火锅','烘焙','便利店'] },
  { key: 'travel',       label: '旅行 / 周边游', en: 'Travel', emoji: '🌊',
    kw: ['旅行','济州岛','安吉','九溪','徒步','周边游','海边','攻略','酒店','机票','Citywalk'.toLowerCase(),'风景','日落','日出','爬山','公园'] },
  { key: 'daily',        label: '生活日常 / vlog', en: 'Daily / Vlog', emoji: '☕',
    kw: ['日常','vlog','独居','周末','生活','记录','下班','宅家','room','收纳','布置','早晨','夜晚'] },
  { key: 'work',         label: '打工人 / 职场', en: 'Work', emoji: '💼',
    kw: ['大厂','打工人','上班','工作','运营','职场','加班','同事','工资','裸辞','辞职','面试','求职','简历'] },
];

function categorize(text) {
  const t = text.toLowerCase();
  let best = null, bestN = 0;
  for (const c of CATS) {
    const n = c.kw.reduce((s, k) => s + (t.includes(k) ? 1 : 0), 0);
    if (n > bestN) { bestN = n; best = c; }
  }
  return best ? best.key : 'other';
}

const median = arr => {
  if (!arr.length) return 0;
  const s = [...arr].sort((a, b) => a - b);
  const m = Math.floor(s.length / 2);
  return s.length % 2 ? s[m] : (s[m - 1] + s[m]) / 2;
};

// analysis files are optional — fold them in when present
const readIf = f => fs.existsSync(path.join(root, f)) ? read(f) : null;

// 蒸馏博主风格档案（styles/ 目录）——供草稿页「借鉴博主」下拉使用
function loadStyles() {
  const out = [];
  const dir = path.join(root, 'styles');
  if (!fs.existsSync(dir)) return out;
  for (const f of fs.readdirSync(dir)) {
    if (!f.endsWith('.json')) continue;
    try {
      const a = JSON.parse(fs.readFileSync(path.join(dir, f), 'utf8'));
      const b = a.博主 || {};
      out.push({ name: b.name || f.replace(/\.json$/, ''), tags: b.赛道标签 || [] });
    } catch {}
  }
  return out;
}
const creatorAnalyses = {};
const caDir = path.join(root, 'analysis', 'creators');
if (fs.existsSync(caDir)) {
  for (const f of fs.readdirSync(caDir)) {
    const m = f.match(/^(.+)-analysis\.json$/);
    if (m) { try { creatorAnalyses[m[1]] = JSON.parse(fs.readFileSync(path.join(caDir, f), 'utf8')); } catch {} }
  }
}
// pulled per-creator notes (top of each, for the detail view)
const creatorNotes = {};
const cnDir = path.join(root, 'creators');
if (fs.existsSync(cnDir)) {
  for (const f of fs.readdirSync(cnDir)) {
    if (!f.endsWith('.json')) continue;
    try {
      const c = JSON.parse(fs.readFileSync(path.join(cnDir, f), 'utf8'));
      creatorNotes[f.replace('.json', '')] = (c.notes || []).slice(0, 30).map(n => ({
        title: n.title, likes: n.likes, saves: n.saves, comments: n.comments,
        shares: n.shares, type: n.type, url: n.url,
      }));
    } catch {}
  }
}

// ── X + Substack creators (with analysis) ────────────────────────────────
function loadPlatform(dir, anaDir, keyField) {
  const out = [];
  const d = path.join(root, dir);
  if (!fs.existsSync(d)) return out;
  for (const f of fs.readdirSync(d)) {
    if (!f.endsWith('.json')) continue;
    try {
      const c = JSON.parse(fs.readFileSync(path.join(d, f), 'utf8'));
      const key = c[keyField];
      const ana = path.join(root, anaDir, `${key}-analysis.json`);
      c.analysis = fs.existsSync(ana) ? JSON.parse(fs.readFileSync(ana, 'utf8')) : null;
      out.push(c);
    } catch {}
  }
  return out;
}
const xCreators = loadPlatform('creators_x', 'analysis/x', 'handle')
  .map(c => ({ handle: c.handle, name: c.name, desc: c.desc, avatar: c.avatar,
    followers: c.followers, analysis: c.analysis,
    posts: (c.tweets || []).slice(0, 10).map(t => ({ text: t.text, likes: t.likes,
      retweets: t.retweets, bookmarks: t.bookmarks, replies: t.replies, views: t.views, url: t.url })) }))
  .sort((a, b) => b.followers - a.followers);
const subCreators = loadPlatform('creators_sub', 'analysis/sub', 'slug')
  .map(c => ({ slug: c.slug, name: c.name, desc: c.desc, avatar: c.avatar, feed: c.feed,
    analysis: c.analysis, posts: (c.posts || []).slice(0, 10) }));

// ── creators → data.js ──────────────────────────────────────────────────
{
  const raw = readIf('xhs_authors.json') || [];
  const creators = raw.map(a => {
    // Prefer deep-pull data when available; fall back to the rough tally from
    // the discovery search so every author has a rough type label.
    const deepNotes = creatorNotes[a.id] || [];
    const vidCount = deepNotes.length
      ? deepNotes.filter(p => p.type === 'video').length
      : (a.vid || 0);
    const total = deepNotes.length || ((a.vid || 0) + (a.img || 0));
    return {
      name: a.name, id: a.id, avatar: a.avatar || '',
      kws: a.kws, eng: a.eng, col: a.col, hits: a.hits, titles: a.titles || [],
      analysis: creatorAnalyses[a.id] || null,
      posts: deepNotes.length ? deepNotes : null,
      // video ratio among known posts: 1 = pure video blogger, 0 = pure image-text.
      // null = absolutely no data (rare)
      vr: total ? vidCount / total : null,
    };
  });
  const keywords = [...new Set(creators.flatMap(c => c.kws))].sort();
  write('data.js', {
    landscape: readIf('analysis/landscape.json'),
    xLandscape: readIf('analysis/x-landscape.json'),
    subLandscape: readIf('analysis/sub-landscape.json'),
    x: xCreators,
    sub: subCreators,
    vault: readIf('vault/vault.json'),
    meta: {
      creators: creators.length,
      notes: creators.reduce((s, c) => s + c.hits, 0),
      keywords: keywords.length,
      likes: creators.reduce((s, c) => s + c.eng, 0),
      saves: creators.reduce((s, c) => s + c.col, 0),
      costUsd: +(keywords.length * 0.001).toFixed(3),
    },
    keywords, creators,
    styles: loadStyles(),
  });
  console.log(`data.js  → ${creators.length} creators (${creators.filter(c => c.avatar).length} with avatars)`);
}

// ── my notes → me.js ────────────────────────────────────────────────────
{
  const { profile = {}, notes = [] } = readIf('me.json') || {};

  const engAll = notes.map(n => n.likes + n.saves + n.comments + n.shares);
  const medEng = median(engAll);
  const medSaveRate = median(notes.filter(n => n.likes).map(n => n.saves / n.likes));

  const enriched = notes.map(n => {
    const eng = n.likes + n.saves + n.comments + n.shares;
    return {
      ...n,
      cat: categorize(`${n.title} ${n.desc}`),
      eng,
      saveRate: n.likes ? +(n.saves / n.likes).toFixed(2) : 0,
      shareRate: n.likes ? +(n.shares / n.likes).toFixed(3) : 0,
      // outlier vs your own median — this is what /bootstrap-voice should learn from
      outlier: medEng > 0 && eng >= medEng * 3,
    };
  }).sort((a, b) => b.eng - a.eng);

  // per-category rollup
  const byCat = {};
  for (const c of [...CATS, { key: 'other', label: '其他', en: 'Other', emoji: '•' }]) {
    const items = enriched.filter(n => n.cat === c.key);
    if (!items.length) continue;
    byCat[c.key] = {
      label: c.label, en: c.en, emoji: c.emoji, count: items.length,
      likes: items.reduce((s, n) => s + n.likes, 0),
      saves: items.reduce((s, n) => s + n.saves, 0),
      medEng: median(items.map(n => n.eng)),
      top: items[0]?.title || '',
    };
  }

  // monthly time-series (activity is concentrated in the last ~18 months)
  const monthMap = {};
  for (const n of notes) {
    if (!n.created) continue;
    const d = new Date(n.created);
    const k = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`;
    (monthMap[k] ||= []).push(n);
  }
  const months = Object.keys(monthMap).sort();
  // fill gaps between first and last so the axis is continuous
  const series = [];
  if (months.length) {
    let [y, m] = months[0].split('-').map(Number);
    const [ly, lm] = months[months.length - 1].split('-').map(Number);
    while (y < ly || (y === ly && m <= lm)) {
      const k = `${y}-${String(m).padStart(2, '0')}`;
      const items = monthMap[k] || [];
      const engs = items.map(n => n.likes + n.saves + n.comments + n.shares);
      series.push({
        month: k, count: items.length,
        likes: items.reduce((s, n) => s + n.likes, 0),
        saves: items.reduce((s, n) => s + n.saves, 0),
        comments: items.reduce((s, n) => s + n.comments, 0),
        shares: items.reduce((s, n) => s + n.shares, 0),
        medEng: median(engs),
      });
      m++; if (m > 12) { m = 1; y++; }
    }
  }

  write('me.js', {
    profile,
    analysis: readIf('analysis/me-analysis.json'),
    voice: readIf('voice/voice.json'),
    drafts: readIf('drafts/index.json'),
    materials: readIf('materials/materials.json'),
    series,
    stats: {
      notes: notes.length,
      videos: notes.filter(n => n.type === 'video').length,
      medEng, medSaveRate: +medSaveRate.toFixed(2),
      totalLikes: notes.reduce((s, n) => s + n.likes, 0),
      totalSaves: notes.reduce((s, n) => s + n.saves, 0),
      totalShares: notes.reduce((s, n) => s + n.shares, 0),
    },
    cats: CATS.map(c => ({ key: c.key, label: c.label, en: c.en, emoji: c.emoji })),
    byCat,
    notes: enriched,
  });
  console.log(`me.js    → ${profile.name || '(空)'}: ${notes.length} notes, ${Object.keys(byCat).length} categories, median engagement ${medEng}`);
  console.log('           categories:', Object.entries(byCat).map(([k, v]) => `${v.emoji}${v.count}`).join(' '));
}
